name: deploy-to-eb

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create ZIP deployment package
        run: zip -r deploy_package.zip ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACESSKEYID }}
          aws-secret-access-key: ${{ secrets.SECRETACCESSKEY }}
          aws-region: "us-east-2"

      - name: Upload package to S3 bucket
        run: aws s3 cp deploy_package.zip s3://code-aws-prova/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name AWSprova \
          --source-bundle S3Bucket="code-aws-prova",S3Key="deploy_package.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name Awsprova-env --version-label "Sample Application"